import assert from 'node:assert/strict';
import { randomUUID, randomBytes } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { PrismaClient } from '@prisma/client';
const base = process.env.ADMIN_TEST_API || 'http://127.0.0.1:3002/api/v1';
if (!['localhost', '127.0.0.1'].includes(new URL(base).hostname) || !process.env.DATABASE_URL?.endsWith('/tt_rental_admin_dev')) throw new Error('This suite only runs against the isolated local admin database.');
const db = new PrismaClient();
const run = randomBytes(4).toString('hex');
const results = [];
const today = new Date(new Intl.DateTimeFormat('en-CA', {timeZone:'Asia/Ho_Chi_Minh'}).format(new Date())+'T00:00:00Z');
const day = n => new Date(+today+n*86400000).toISOString().slice(0,10);
async function request(path, method = 'GET', data, token, expected = 200) {
  const response = await fetch(base+path, {method, headers: {'content-type':'application/json', ...(token ? {authorization:`Bearer ${token}`} : {})}, body: data === undefined ? undefined : JSON.stringify(data)});
  const body = await response.json();
  assert.equal(response.status, expected, `${method} ${path}: ${JSON.stringify(body)}`);
  return body.data;
}
async function test(name, fn) { try { await fn(); results.push({name,passed:true}); console.log('PASS '+name); } catch(error) { results.push({name,passed:false,error:error.message}); throw error; } }
let admin, actor, customer, unit, property, location, booking, staff, role, staffToken, readRole, customerToken, block, quote;
const stay = () => ({unitId:unit.id,checkIn:day(0),checkOut:day(2),guestCount:2});
const req = (p,m,d,status) => request('/admin'+p,m,d,admin,status??(m==='POST'?201:200));
const transition = (status, expected=200) => req(`/bookings/${booking.id}/status`,'PATCH',{status,reason:'QA lifecycle '+run},expected);
try {
  await test('Unauthenticated admin API is rejected', () => request('/admin/bookings','GET',undefined,undefined,401));
  await test('Incorrect password is rejected', () => request('/auth/login','POST',{email:process.env.ADMIN_EMAIL,password:'invalid-password'},undefined,401));
  await test('Admin login and permission session', async()=>{admin=(await request('/auth/login','POST',{email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD},undefined,201)).accessToken; actor=await req('/session'); assert(actor.permissions.includes('staff.manage'));});
  await test('Customer account cannot use admin session', async()=>{customerToken=(await request('/auth/register','POST',{email:`customer-${run}@example.test`,password:'Customer-test-'+run,firstName:'QA',lastName:'Customer',phone:'0900000000'},undefined,201)).accessToken;await request('/admin/session','GET',undefined,customerToken,403);await request('/admin/bookings','GET',undefined,customerToken,403);});
  await test('List dashboard, customers, catalog, calendar, payment and audit', async()=>{for (const p of ['/dashboard','/customers','/units','/properties','/calendar','/payments','/staff','/audit']) await req(p);location=(await req('/locations'))[0];assert(location);});
  await test('Create property', async()=>{property=await req('/properties','POST',{name:`QA Property ${run}`,locationId:location.id,address:'QA local property, Da Nang',latitude:16.0544,longitude:108.2022,checkInTime:'14:00',checkOutTime:'11:00',status:'ACTIVE'});assert(property.id);});
  await test('Edit property and validate invalid coordinates', async()=>{const dto={name:property.name+' updated',locationId:location.id,address:property.address,latitude:16.0544,longitude:108.2022,checkInTime:'15:00',checkOutTime:'11:00',status:'ACTIVE'};property=await req(`/properties/${property.id}`,'PATCH',dto);assert.equal(property.checkInTime,'15:00');await req('/properties','POST',{...dto,latitude:200},400);});
  await test('Create apartment with fees and deposit', async()=>{unit=await req('/units','POST',{propertyId:property.id,publicCode:`QA-${run}`,nameVi:'QA Apartment '+run,status:'PUBLISHED',bedroomCount:1,bathroomCount:1,bedCount:1,maxGuests:2,area:40,currency:'VND',basePrice:1000000,cleaningFee:100000,serviceFeeRate:0.05,depositRate:0.3});assert(unit.id);});
  await test('Duplicate apartment code rejected', ()=>req('/units','POST',{propertyId:property.id,publicCode:unit.publicCode,nameVi:'Duplicate',status:'DRAFT',bedroomCount:1,bathroomCount:1,bedCount:1,maxGuests:2,area:40,currency:'VND',basePrice:1000000,cleaningFee:0,serviceFeeRate:0,depositRate:0},409));
  await test('Create customer', async()=>{customer=await req('/customers','POST',{firstName:'Khách thử',lastName:'QA',phone:'0900000000',email:`guest-${run}@example.test`,notes:'QA local only'});assert(customer.id);});
  await test('Update customer and clear optional email / note', async()=>{customer=await req(`/customers/${customer.id}`,'PATCH',{firstName:'Khách thử',lastName:'QA',phone:'0900000001',email:null,notes:''});assert.equal(customer.email,null);assert.equal(customer.notes,'');});
  await test('Reject blank name and malformed email', async()=>{await req('/customers','POST',{firstName:'   ',lastName:'QA',phone:'0900000000'},400);await req('/customers','POST',{firstName:'QA',lastName:'Guest',phone:'0900000000',email:'bad'},400);});
  await test('Reject invalid stay dates / capacity / extra fields', async()=>{for (const input of [{...stay(),checkIn:day(2),checkOut:day(1)},{...stay(),checkIn:'2027-02-30',checkOut:'2027-03-04'},{...stay(),guestCount:3},{...stay(),total:1}]) await req('/quote','POST',input,400);});
  await test('Authoritative quote includes fees and required deposit', async()=>{quote=await req('/quote','POST',stay());assert.equal(Number(quote.total),2200000);assert.equal(Number(quote.requiredDeposit),660000);assert.equal(quote.nights,2);});
  await test('Reject stale quote after price change', async()=>{await req(`/units/${unit.id}`,'PATCH',{nameVi:unit.nameVi,basePrice:1100000,maxGuests:2,status:'PUBLISHED'});await req('/bookings','POST',{...stay(),customerId:customer.id,source:'PHONE',quoteId:quote.quoteId},409);await req(`/units/${unit.id}`,'PATCH',{nameVi:unit.nameVi,basePrice:1000000,maxGuests:2,status:'PUBLISHED'});});
  await test('Create booking from valid quote', async()=>{quote=await req('/quote','POST',stay());booking=await req('/bookings','POST',{...stay(),customerId:customer.id,source:'PHONE',quoteId:quote.quoteId});assert.equal(booking.status,'PENDING_PAYMENT');assert.equal(Number(booking.remainingAmount),2200000);});
  await test('Prevent overlapping booking / maintenance', async()=>{await req('/quote','POST',stay(),409);await req('/blocks','POST',{unitId:unit.id,checkIn:day(1),checkOut:day(3),state:'MAINTENANCE',reason:'QA overlap'},409);});
  await test('Allow adjacent stay starting on checkout day', ()=>req('/quote','POST',{...stay(),checkIn:day(2),checkOut:day(3)}));
  await test('Cannot confirm before deposit', ()=>transition('CONFIRMED',400));
  await test('Cannot skip directly to check-in', ()=>transition('CHECKED_IN',400));
  await test('Reject negative and excessive payment', async()=>{for (const amount of [-1,3000000]) await req(`/bookings/${booking.id}/payments`,'POST',{amount,method:'CASH',reference:'QA test',requestId:randomUUID()},400);});
  await test('Deposit payment is idempotent', async()=>{const payment={amount:660000,method:'BANK_TRANSFER',reference:'QA receipt '+run,requestId:randomUUID()};const a=await req(`/bookings/${booking.id}/payments`,'POST',payment);const b=await req(`/bookings/${booking.id}/payments`,'POST',payment);assert.equal(a.id,b.id);const saved=await db.booking.findUniqueOrThrow({where:{id:booking.id}});assert.equal(Number(saved.paidAmount),660000);await req(`/bookings/${booking.id}/payments`,'POST',{...payment,amount:1},409);});
  await test('Confirm after deposit and check in', async()=>{assert.equal((await transition('CONFIRMED')).status,'CONFIRMED');assert.equal((await transition('CHECKED_IN')).status,'CHECKED_IN');});
  await test('Cannot check out before balance is paid', ()=>transition('CHECKED_OUT',400));
  await test('Collect balance, check out, complete', async()=>{await req(`/bookings/${booking.id}/payments`,'POST',{amount:1540000,method:'CASH',reference:'QA balance',requestId:randomUUID()});assert.equal((await transition('CHECKED_OUT')).status,'CHECKED_OUT');assert.equal((await transition('COMPLETED')).status,'COMPLETED');});
  await test('Completed booking cannot be changed or paid again', async()=>{await transition('CHECKED_IN',400);await req(`/bookings/${booking.id}/payments`,'POST',{amount:1,method:'CASH',reference:'QA invalid',requestId:randomUUID()},400);});
  await test('Block and unblock room', async()=>{block=await req('/blocks','POST',{unitId:unit.id,checkIn:day(5),checkOut:day(7),state:'MAINTENANCE',reason:'QA maintenance'});await req('/quote','POST',{...stay(),checkIn:day(5),checkOut:day(6)},409);assert((await req('/calendar')).blocks.some(b=>b.id===block.id));await req(`/blocks/${block.id}`,'DELETE');await req('/quote','POST',{...stay(),checkIn:day(5),checkOut:day(6)});});
  await test('Draft apartment cannot be booked', async()=>{await req(`/units/${unit.id}`,'PATCH',{nameVi:unit.nameVi,basePrice:1000000,maxGuests:2,status:'DRAFT'});await req('/quote','POST',{...stay(),checkIn:day(5),checkOut:day(6)},400);await req(`/units/${unit.id}`,'PATCH',{nameVi:unit.nameVi,basePrice:1000000,maxGuests:2,status:'PUBLISHED'});});
  await test('Create custom role and reject duplicate / invalid permissions', async()=>{role=await req('/roles','POST',{code:`QA_${run.toUpperCase()}`,name:'QA Reception '+run,permissions:['booking.read','availability.read']});await req('/roles','POST',{code:role.code,name:'Duplicate',permissions:['booking.read']},409);await req('/roles','POST',{code:'QA_UNKNOWN_'+run.toUpperCase(),name:'Invalid',permissions:['invented.permission']},403);});
  await test('Create staff and authenticate with scoped permissions', async()=>{staff=await req('/staff','POST',{firstName:'QA',lastName:'Staff',email:`staff-${run}@example.test`,password:'QA-staff-pass-'+run,roleId:role.id});staffToken=(await request('/auth/login','POST',{email:staff.email,password:'QA-staff-pass-'+run},undefined,201)).accessToken;await request('/admin/bookings','GET',undefined,staffToken);});
  await test('Staff cannot access financials, staff list, customer list or mutate', async()=>{for(const p of ['/payments','/staff','/customers','/dashboard','/audit']) await request('/admin'+p,'GET',undefined,staffToken,403);await request('/admin/customers','POST',{firstName:'Bad',lastName:'Actor',phone:'0900000000'},staffToken,403);await request(`/admin/bookings/${booking.id}/status`,'PATCH',{status:'CHECKED_IN',reason:'Forbidden'},staffToken,403);});
  await test('Protected owner and self cannot be reassigned', async()=>{await req(`/staff/${actor.id}`,'PATCH',{roleId:role.id,status:'DISABLED'},403);const ownerRole=(await req('/staff')).roles.find(r=>r.code==='ADMIN_OWNER');await req('/staff','POST',{firstName:'Bad',lastName:'Owner',email:`owner-${run}@example.test`,password:'QA-owner-pass-'+run,roleId:ownerRole.id},403);});
  await test('Changing role revokes old token and refresh', async()=>{const login=await request('/auth/login','POST',{email:staff.email,password:'QA-staff-pass-'+run},undefined,201);readRole=await req('/roles','POST',{code:`READ_${run.toUpperCase()}`,name:'QA Calendar only '+run,permissions:['availability.read']});await req(`/staff/${staff.id}`,'PATCH',{roleId:readRole.id,status:'ACTIVE'});await request('/admin/bookings','GET',undefined,login.accessToken,401);await request('/auth/refresh','POST',{refreshToken:login.refreshToken},undefined,401);const fresh=(await request('/auth/login','POST',{email:staff.email,password:'QA-staff-pass-'+run},undefined,201)).accessToken;await request('/admin/bookings','GET',undefined,fresh,403);await request('/admin/calendar','GET',undefined,fresh);staffToken=fresh;});
  await test('Disabling staff revokes session and prevents login', async()=>{await req(`/staff/${staff.id}`,'PATCH',{roleId:readRole.id,status:'DISABLED'});await request('/admin/calendar','GET',undefined,staffToken,401);await request('/auth/login','POST',{email:staff.email,password:'QA-staff-pass-'+run},undefined,401);});
  await test('Invalid IDs and missing entities return meaningful errors', async()=>{await req('/blocks/not-a-uuid','DELETE',undefined,400);await req('/blocks/'+randomUUID(),'DELETE',undefined,404);});
  await test('Concurrent double booking allows only one winner', async()=>{const input={...stay(),checkIn:day(10),checkOut:day(12)};const a=await req('/quote','POST',input),b=await req('/quote','POST',input);const responses=await Promise.all([a,b].map(q=>fetch(base+'/admin/bookings',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${admin}`},body:JSON.stringify({...input,customerId:customer.id,source:'PHONE',quoteId:q.quoteId})})));assert.equal(responses.filter(r=>r.status===201).length,1);assert.equal(responses.filter(r=>r.status===409).length,1);const winner=await responses.find(r=>r.status===201).json();await req(`/bookings/${winner.data.id}/status`,'PATCH',{status:'CANCELLED_BY_STAFF',reason:'QA cancelled booking'});await req('/quote','POST',input);});
  await test('Concurrent payment requests never double-count the same receipt', async()=>{const input={...stay(),checkIn:day(15),checkOut:day(17)};const q=await req('/quote','POST',input);const b=await req('/bookings','POST',{...input,customerId:customer.id,source:'PHONE',quoteId:q.quoteId});const payment={amount:660000,method:'CASH',reference:'QA concurrent',requestId:randomUUID()};const responses=await Promise.all([1,2].map(()=>fetch(base+`/admin/bookings/${b.id}/payments`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${admin}`},body:JSON.stringify(payment)})));assert(responses.every(r=>[201,409].includes(r.status)));assert.equal(Number((await db.booking.findUniqueOrThrow({where:{id:b.id}})).paidAmount),660000);await req(`/bookings/${b.id}/status`,'PATCH',{status:'CANCELLED_BY_STAFF',reason:'QA cancelled with paid deposit'});});
  await test('Audit contains all important mutations', async()=>{const audit=await req('/audit');for(const action of ['booking.create','booking.update','booking.checkin','booking.checkout','booking.cancel','payment.confirm','customer.create','customer.update','unit.create','unit.update','property.create','property.update','availability.block','availability.unblock','staff.create','staff.access','role.create']) assert(audit.some(a=>a.action===action),'Missing '+action);});
  console.log(`${results.length}/${results.length} admin integration checks passed.`);
} finally {
  await writeFile(new URL('../docs/ADMIN_API_TEST_RESULTS.md',import.meta.url), '# Admin integration test results\n\nEnvironment: isolated local PostgreSQL + NestJS API.\n\nRun: '+new Date().toISOString()+'\n\n'+results.map(r=>`- ${r.passed?'PASS':'FAIL'}: ${r.name}${r.error?' — '+r.error:''}`).join('\n')+'\n');
  await db.$disconnect();
}
